version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: horarios_db
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - horarios_db
    environment:
      PMA_HOST: horarios_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata:
