definitions:
  domain.AvailableHours:
    properties:
      kind:
        type: integer
      max:
        type: integer
      remaining:
        type: integer
      subject:
        type: string
    type: object
  handlers.ErrorHttp:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /availableHours/:
    get:
      description: List all the hours remaining for creaiting an entrie on the schedule
      parameters:
      - description: titulacion de las horas a obtener
        in: query
        name: titulacion
        required: true
        type: string
      - description: curso de las horas a obtener
        in: query
        name: curso
        required: true
        type: integer
      - description: grupo de las horas a obtener
        in: query
        name: grupo
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.AvailableHours'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorHttp'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handlers.ErrorHttp'
swagger: "2.0"
