name: Go_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Test
      run: docker compose up -d; cd src/pkg/sql/ ; ./drop.sh ; ./create.sh ; cd - ; go test -v ./...
